### ISSUE TITLE
TypeError: Cannot interpret 'torch.float32' as a data type

### ISSUE THREAD

**Issue by Muhammad-Raza156** [kbressem/prostate158#1]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/38157696/189404791-d8eb563f-c8d5-4406-b404-db26b6dd1634.png">
this error occurred while running the code

**Comment by kbressem** [comment]
Are you using MONAI > 0.9. There were breaking changes with the introduction of `MetaTensor`.

**Comment by Muhammad-Raza156** [comment]
I am using MONAI 0.6.0.

**Comment by kbressem** [comment]
I have not tested the code with any other version as given in: 
https://github.com/kbressem/prostate158#dependencies

Please try to update your environment. Hopefully, this will resolve the issue.

**Comment by Muhammad-Raza156** [comment]
I will try it.

**Comment by kbressem** [comment]
Did it work?

**Comment by kbressem** [comment]
Feel free to reopen the issue, if you need more help.
