### ISSUE TITLE
Where can CSV files be downloaded?

### ISSUE THREAD

**Issue by shebna12** [kbressem/prostate158#2]
Hi! Thank you for your efforts in creating this repo with a detailed README guide. I'd like to know where I can download the `train.csv`, `test.csv`, and `valid.csv`? I'm getting this error when I run the SegmentationTrainer:
`FileNotFoundError: [Errno 2] No such file or directory: 'prostate158/train.csv'`

**Comment by kbressem** [comment]
The csv files are provided with the data, which you can access here: https://zenodo.org/record/6481141
