### ISSUE TITLE
Testing on external dataset

### ISSUE THREAD

**Issue by ericKuo722** [kbressem/prostate158#3]
Hi, I'm now trying to test the model you provided on the PI-CAI dataset. Could you please let me know what does the test csv file look like? Thank you very much! 
I have seen the yaml file but still cannot figure it out by myself.

**Comment by kbressem** [comment]
You can get the csv's for the test set, I have used here: 
https://doi.org/10.5281/zenodo.6592345

basically it is a simple table like this: 

|  image  |  label  |
|---------|---------|
| path/to/image/ |  path/to/label |


For PI-CAI you will need to do the data wrangling yourself.

**Comment by ericKuo722** [comment]
Thanks for responding me so quickly! I see, I will check this test data. 
Thank you very much!
