### ISSUE TITLE
y_pred and y should have same shapes.

### ISSUE THREAD

**Issue by ericKuo722** [kbressem/prostate158#4]
File /.local/lib/python3.8/site-packages/monai/metrics/meandice.py", line 123, in compute_meandice
    raise ValueError("y_pred and y should have same shapes.")
ValueError: y_pred and y should have same shapes.

Hi, I'm now validating the tumor.pt model on PI-CAI dataset. I have done resampled, centre-cropping (MRIs, annotations). I have replace labels to 0 and 1 only. I have checked every data are in the same shape for each patient. But this error happens, could you please let me know what I have missed? I'm also searching online but I wonder maybe you had this issue before. Thank you very much!

**Comment by kbressem** [comment]
This means, your predictions do not have the same shape as the labels. This can be a resampling error in the U-Net, if the input resolution is not divisible by `stride_size * n_strides`. In this case, try other input resolutions. 
If you could paste your config, I might be able to spot the error.

**Comment by ericKuo722** [comment]
Is this the config you are asking for? This is the output config file. The original tumor.yaml file I used is the same as yours, the only difference is the path of testing dataset.

data:
  batch_size: 1
  cache_dir: /tmp/monai-cache
  data_dir: dataset
  dataset_type: persistent
  image_cols:
  - t2
  - adc
  - dwi
  label_cols:
  - adc_tumor_reader1
  test: false
  test_csv: dataset/external/external.csv
  train: true
  train_csv: dataset/train/train.csv
  valid: true
  valid_csv: dataset/train/valid.csv
debug: false
device: cuda
log_dir: tumor_1/logs
loss:
  DiceFocalLoss:
    include_background: false
    softmax: true
    to_onehot_y: true
lr_scheduler:
  OneCycleLR:
    max_lr: 0.001
model:
  act: PRELU
  channels:
  - 16
  - 32
  - 64
  - 128
  - 256
  - 512
  dropout: 0.15
  norm: BATCH
  num_res_units: 4
  out_channels: 2
  strides:
  - 2
  - 2
  - 2
  - 2
  - 2
model_dir: models
ndim: 3
optimizer:
  Novograd:
    amsgrad: true
    lr: 0.001
    weight_decay: 0.01
out_dir: tumor_1/output
overwrite: false
run_id: tumor_1
seed: 42
training:
  early_stopping_patience: 1000
  max_epochs: 500
transforms:
  adjust_contrast:
    gamma: 2.0
  gaussian_noise:
    mean: 0.1
    std: 0.25
  gaussian_sharpen:
    alpha:
    - 10.0
    - 30.0
    sigma1_x:
    - 0.5
    - 1.0
    sigma1_y:
    - 0.5
    - 1.0
    sigma1_z:
    - 0.5
    - 1.0
    sigma2_x:
    - 0.5
    - 1.0
    sigma2_y:
    - 0.5
    - 1.0
    sigma2_z:
    - 0.5
    - 1.0
  mode:
  - bilinear
  - bilinear
  - bilinear
  - nearest
  orientation: RAS
  prob: 0.175
  rand_affine:
    rotate_range: 5
    shear_range: 0.5
    translate_range: 25
  rand_bias_field:
    coeff_range:
    - 0.0
    - 0.01
    degree: 10
  rand_elastic:
    magnitude_range:
    - 0.5
    - 1.5
    rotate_range: 5
    shear_range: 0.5
    sigma_range:
    - 0.5
    - 1.5
    translate_range: 25
  rand_gaussian_smooth:
    sigma_x:
    - 0.25
    - 1.5
    sigma_y:
    - 0.25
    - 1.5
    sigma_z:
    - 0.25
    - 1.5
  rand_gibbs_nose:
    alpha:
    - 0.5
    - 1
  rand_rotate:
    range_x: 0.1
    range_y: 0.1
    range_z: 0.1
  rand_rotate90:
    spatial_axes:
    - 0
    - 1
  rand_spatial_crop_samples:
    num_samples: 8
    roi_size:
    - 96
    - 96
    - 96
  rand_zoom:
    max: 1.1
    min: 0.9
  shift_intensity:
    offsets: 0.2
  spacing:
  - 0.5
  - 0.5
  - 0.5

**Comment by ericKuo722** [comment]
Also, if this information helps.

These are the shape of input, tuples in the front are the shape, and the following are how many of that shape cases.
{(192, 192): 666,
 (320, 320): 302,
 (512, 512): 226,
 (160, 160): 79,
 (384, 384): 18,
 (256, 256): 2,
 (128, 128): 2}
 
 These are the shape of prostate158 input.
 {(270, 270): 83, (442, 442): 26, (232, 232): 10}

**Comment by kbressem** [comment]
Shouldn't the shapes have 3 dimensions? The down-/up-sizing also happens alongside the z-axis. 
Can you provide the size of the predictions and the label? 
If it is only off by one or two px, it is likely due to the resizing in the U-Net. In this case you may want to just resize the preds to match the labels.

**Comment by ericKuo722** [comment]
Yes, they are 3 dim but I only print 2 dim out.  These are the shapes of input data.
[(128, 128, 33),
 (160, 160, 19),
 (160, 160, 21),
 (160, 160, 22),
 (160, 160, 23),
 (160, 160, 25),
 (192, 192, 19),
 (192, 192, 21),
 (192, 192, 23),
 (192, 192, 25),
 (192, 192, 27),
 (192, 192, 31),
 (192, 192, 33),
 (320, 320, 19),
 (320, 320, 25),
 (320, 320, 31),
 (320, 320, 33),
 (320, 320, 35),
 (320, 320, 37),
 (384, 384, 27),
 (384, 384, 29),
 (384, 384, 31),
 (384, 384, 35),
 (512, 512, 27),
 (512, 512, 29)]

Sorry, I'm trying to find where can I print out the shape of predictions and labels but couldn't find out.
