### ISSUE TITLE
RuntimeError: Given transposed=1, weight of size [768, 128, 3, 3, 3], expected input[4, 512, 3, 3, 3] to have 768 channels, but got 512 channels instead

### ISSUE THREAD

**Issue by Martiniger** [kbressem/prostate158#5]
Hello, I trained the model and I am having a problem evaluating it, because I get the following error:

RuntimeError: Given transposed=1, weight of size [768, 128, 3, 3, 3], expected input[4, 512, 3, 3, 3] to have 768 channels, but got 512 channels instead

I don't really know where the problem is and I would really appreciate your help.

![error](https://github.com/kbressem/prostate158/assets/121456655/ef347024-bc58-4bcd-957e-e8de3e84c785)

**Comment by kbressem** [comment]
Can you provide more information (config file and code)

**Comment by Martiniger** [comment]
I used the code provided here and the config file is obtained from the anatomy.yaml file (I didn't change anything except for the paths)

**Comment by kbressem** [comment]
Sorry, for the late reply. It's hard for me to reproduce. In the screenshot you send me, you cut off the top so I cannot see were it goes wrong in the library but it only shows me the stack trace within PyTorch. 
This error is within the neural network configuration. Which is strange, as the same config is used for training and inference. But maybe it will become clear, when I can see where exactly it goes wrong in the library.
