### ISSUE TITLE
Request for label number and class relation

### ISSUE THREAD

**Issue by Jefferyy-Peng** [kbressem/prostate158#8]
Hi, could you provide the corresponding relation between the label digit and the class name in the dataset? If it's already public, could you point me to the link? Thank you very much!

**Comment by kbressem** [comment]
For the anatomy, peripheral zone is `1`, if I remember correctly. Transitional zone is `2`. 
If you look at this GIF: https://github.com/kbressem/prostate158?tab=readme-ov-file#how-to-reproduce-the-baseline

The peripheral zone is the bright U-shaped area, transitional zone is the grey round area. 

The tumor annotations are binary with `1` corresponding to the tumor and `0` to the background.

**Comment by Jefferyy-Peng** [comment]
"Pixelwise segmentations were provided for the central gland (central zone and transitional zone), peripheral zone, and PCa lesions". This is what I found in your dataset paper. I would assume the Transitional zone you mention correspond to the central gland and peripheral zone is just the peripheral zone. Is that correct?

**Comment by kbressem** [comment]
Yes, exactly.
